# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    #- name: Run a one-line script
    #  run: echo Hello, world!

    - name: Show environment
      run: |
        # pwd     # /home/runner/work/demo-actions/demo-actions
        # whoami  # runner
        #uptime
        #which perl
        #which python
        #which python3
        #which ruby
        #which node
        #which java
        #perl -v
        # python -V # 2.7.17
        #python3 -V
        which pip /usr/bin/pip

    - name: Setup
      run: |
        pip install pytest


    #- name: Run tests
    #  run: pytest

  pybuild:
    runs-on: python
    steps:
    - name: Show environment
      run: |
        which python
        python -V
